---
title: "rhizobia.plant.individual_sd_03022023"
author: "Caleb Hill"
date: "2023-02-03"
output: html_document
editor_options:
  chunk_output_Type: console
  chunk_output_type: console
---

## Clear workspace and set directory

```{r setup}

rm(list=ls())
getwd() #clear workspace and set directory

# will need to update following line to map to your files
setwd("/Users/User/Desktop/thesis_stuff/R_working")
# setwd("~/Github/rhizo.rb.tnseq")

## Load packages and functions

# these are packages that you might need for data wrangling, etc.
require("png")
require("dplyr")
require("grid")
require("ggplot2")
require("qqplotr")
library("car")
library("tidyverse")

# load plant data

data <- read.csv("rhizobia.plant.individual.csv")

## Convert to factor/date variable


data$ID<-as.factor(data$ID)
data$microbe<-as.factor(data$microbe)
data$plant<-as.factor(data$plant)
data$nitrogen<-as.factor(data$nitrogen)
data$date<-as.Date(data$date, format = "%m/%d/%Y")

st.date = as.Date("7/13/2022",format="%m/%d/%Y")

data$date <- data$date-st.date #convert to days post inoculation

data$date <- as.numeric(as.character(gsub(" days",replacement = "",x=data$date)))



```

```{r}
#############################


# Computes SD within  each pot of three plants for each relevant measure


individual_pot_plot <- data %>%
     group_by(ID) %>% 
     summarise(microbe = microbe, nitrogen = nitrogen, meanheight = mean(height), SDheight=sd(height), stabilityheight = ((1/SDheight) / meanheight), meanchloro = mean(chlorophyll), SDchloro=sd(chlorophyll), stabilitychloro = ((1/SDchloro) / meanchloro), meanleaves = mean(leaves), SDleaves=sd(leaves), stabilityleaves = ((1/SDleaves) / meanleaves))  #groups data according to pot and calculates mean and SD for each stat for each pot

potdata <- individual_pot_plot %>% distinct() # cleans up duplicate rows in dataframe

leafcount<-data %>% dplyr::filter(microbe == "lib") #creates histogram of leaf count data, including only the library dataset

hist(leafcount$leaves, ylim=c(0,20)) #histogram

#stability measure--inverse coefficient of variation

stabilitydata<-potdata %>% dplyr::filter(microbe == "lib")

ggplot(data=stabilitydata, aes(x=nitrogen, y=stabilityheight, color=nitrogen, fill=nitrogen, shape=nitrogen)) + 
  geom_col(position = position_dodge(), width = 0.75) +
  ylab(expression(atop("Stability of height",paste("(Inverse CV, n = 3)")))) +
  scale_y_continuous(limits=c(0,.007),breaks=seq(0,.007,by=0.001))+
      theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

ggplot(data=stabilitydata, aes(x=nitrogen, y=stabilitychloro, color=nitrogen, fill=nitrogen, shape=nitrogen)) + 
  geom_col(position = position_dodge(), width = 0.75) +
   ylab(expression(atop("Stability of chlorophyll content",paste("(Inverse CV, n = 3)")))) +
  scale_y_continuous(limits=c(0,.008),breaks=seq(0,.008,by=0.001))+
      theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

ggplot(data=stabilitydata, aes(x=nitrogen, y=stabilityleaves, color=nitrogen, fill=nitrogen, shape=nitrogen)) + 
  geom_col(position = position_dodge(), width = 0.75) +
   ylab(expression(atop("Stability of leaf count",paste("(Inverse CV, n = 3)")))) +
  scale_y_continuous(limits=c(0,.003),breaks=seq(0,.003,by=0.001))+
      theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

#these plots are very rough atm, just trying to mess around with ways to display stability

ttest_stabheight <- t.test(stabilityheight ~ nitrogen, data=stabilitydata, var.equal=FALSE)

ttest_stabchloro <- t.test(stabilitychloro ~ nitrogen, data=stabilitydata, var.equal=FALSE)

ttest_stableaves <- t.test(stabilityleaves ~ nitrogen, data=stabilitydata, var.equal=FALSE)

ttest_stabheight
ttest_stabchloro
ttest_stableaves


```

```{r}

#column plots of mean height, chlorophyll content, leaf count

ggplot(data=subset(potdata, as.numeric(potdata$ID) <= 10), aes(x=nitrogen, y=meanheight, color=ID, fill=ID, shape=nitrogen)) + 
  geom_col(position = position_dodge(), width = 0.75) +
  geom_errorbar(aes(ymin=meanheight-SDheight, ymax=meanheight+SDheight), width = 0.2, fill="black", color="black", position = position_dodge(0.75)) +
    ylab(expression(atop("Mean height per pot [cm]",paste("(n = 3)")))) +
  scale_y_continuous(limits=c(-10,90),breaks=seq(0,80,by=10))+
      theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

ggplot(data=subset(potdata, as.numeric(potdata$ID) <= 10), aes(x=nitrogen, y=meanchloro, color=ID, fill=ID, shape=nitrogen)) + 
  geom_col(position = position_dodge(), width = 0.75) +
  geom_errorbar(aes(ymin=meanchloro-SDchloro, ymax=meanchloro+SDchloro), width = 0.2, fill="black", color="black", position = position_dodge(0.75)) +
      ylab(expression(atop("Mean chlorophyll content per pot [SPAD]",paste("(n = 3)")))) +
  scale_y_continuous(limits=c(-10,90),breaks=seq(0,80,by=10))+
      theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

ggplot(data=subset(potdata, as.numeric(potdata$ID) <= 10), aes(x=nitrogen, y=meanleaves, color=ID, fill=ID, shape=nitrogen)) + 
  geom_col(position = position_dodge(), width = 0.75) +
  geom_errorbar(aes(ymin=meanleaves-SDleaves, ymax=meanleaves+SDleaves), width = 0.2, fill="black", color="black", position = position_dodge(0.75)) +
      ylab(expression(atop("Mean leaf count per pot",paste("(n = 3)")))) +
  scale_y_continuous(limits=c(-10,300),breaks=seq(0,300,by=50))+
      theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

#individual plant plots

setwd("/Users/User/Desktop/thesis_stuff/R_working")

indivdata <- read.csv("rhizobia.individual.byplant.csv")

ggplot(data=subset(indivdata, microbe!="wt"),  aes(x=pot, y=height, color=nitrogen, fill=nitrogen)) +
  geom_col(position = position_dodge(), width = 0.5) +
        ylab(expression(atop("Height [cm] per plant"))) #VERY rough draft... need to be able to show all individual plants GROUPED by pot#, with the lib plants colored by nitrogen and the pbs plants given their own color. Might need to add a sub-ID column to indivdata


# as of 9 feb 2023, still need to figure out some aesthetic things with these plots. Can't get error bars to show up black, not sure about color or layout yet. Pretty but not practical!!

# 13 feb 2023 figured out error bars but still not pleased with the beautiful pastel rainbow plots

```
