---
title: "Plant data analysis RB-TnSeq"
author: "Caleb Hill, John McMullen, Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: inline
---

## Clear workspace and set directory
```{r}
rm(list=ls())
getwd()
# will need to update following line to map to your files
 setwd("~/Github/rhizo.rb.tnseq")


## Load packages and functions

# these are packages that you might need for data wrangling, etc.
require("png")
require("dplyr")
require("grid")
require("ggplot2")
require("qqplotr")
library("car")
library("tidyverse")

# these are functions for summary statistics
 
#LL.95 <- function(x) t.test(x)$conf.int[1]
#UL.95 <- function(x) t.test(x)$conf.int[2]
#sem <- function(x) sqrt(var(x)/length(x))
#cv <- function(x) sd(x)/sqrt(mean(x))
 
CI <- function(x)
  1.96*sd(x)/sqrt(length(x)) #returns the value which is added/subtracted from the mean to yield the CI for the given vector

se <- function(x) {sd(x)/sqrt(length(x))} #returns standard error of the given vector

# load data

data <- read.csv("./Data/rhizobia.plant.csv")


## Convert to factor/date variable

data$microbe<-as.factor(data$microbe)
data$plant<-as.factor(data$plant)
data$nitrogen<-as.factor(data$nitrogen)
data$date<-as.Date(data$date, format = "%m/%d/%Y")

st.date = as.Date("7/13/2022",format="%m/%d/%Y")

data$date <- data$date-st.date #convert to days post inoculation

data$date <- as.numeric(as.character(gsub(" days",replacement = "",x=data$date)))

#variable definitions which subset the data by inoculation and allow easy access for summary stats, plotting etc

libdata <- data %>% filter(microbe=="lib")

apos <- data %>% filter(microbe=="pbs")

height_apos <- mean(apos$height)

chloro_apos <- mean(apos$chlorophyll)

leaves_apos <- mean(apos$leaves)

biomass_apos <- mean(apos$dry.biomass) #aposymbiotic means used in ttest model

#prepare data for plotting

plotmeans_data <- data %>% group_by(microbe, nitrogen) %>% summarise(meanheight=mean(height), CIheight=CI(height), meanchloro=mean(chlorophyll), CIchloro=CI(chlorophyll), meanleaves=mean(leaves), CIleaves=CI(leaves), meanbiomass=mean(dry.biomass), CIbiomass=CI(dry.biomass)) #creates dataframe showing means for all treatment groups

```

``` {r}

#BIOMASS

#Initial assessment of data

ggplot(data=data, aes(x=nitrogen,y=dry.biomass,color=microbe)) +
     geom_boxplot()

ggplot(data=data, aes(x=date,y=dry.biomass,color=microbe,shape=nitrogen)) +
     geom_point() #if there looks to be a trend, add the time in the lm equation 

#Welch's t-test to assess potential association between nitrogen and dry plant biomass, factoring in apo plots by dividing by the average

ttest_mass <- t.test((libdata$dry.biomass/biomass_apos) ~ libdata$nitrogen, data=libdata, var.equal=FALSE)

#Publication-quality plot of means+/-CI for each measurement variable, including apos. Not sure about the purpose of the intercept line or if it looks how it's supposed to? 13 Feb 2023

ggplot(data=subset(plotmeans_data, microbe != "wt"), aes(x=nitrogen, y=meanbiomass, color=microbe)) +
  geom_point(size=3) +
  geom_errorbar(aes(ymin=meanbiomass-CIbiomass, ymax=meanbiomass+CIbiomass), width=0.3) +
  ylab(expression(atop("Biomass [g]",paste("(mean \U00B1 95% CI, n = 5)")))) +
  geom_hline(yintercept=1,linetype=2) +
  scale_y_continuous(limits=c(0,7),breaks=seq(0,7,by=1))+
    theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

#Linear model to generate residuals for normality testing. Log transform was determined unnecessary so was commented out
biomass = lm(dry.biomass ~ nitrogen + date,data=subset(data,microbe=="lib"))
# biomass = lm(log10(dry.biomass) ~ nitrogen,data=data)

summary(biomass)
AIC(biomass)

#assess normality of residuals
biomass_res = residuals(biomass)
summary(biomass_res) 
qqPlot(biomass_res) 
hist(biomass_res) 
boxplot(biomass_res) 
shapiro.test(biomass_res) 
#All looks okay

#assess homoscedasticity of residuals
plot(fitted(biomass),biomass_res);
abline(h=0,lty=2);
lines(smooth.spline(fitted(biomass),biomass_res)); #fairly even spread
leveneTest(biomass_res ~ nitrogen, data = subset(data,microbe=='lib')) #not significant
#All looks okay

#omnibus test
Anova(biomass)

#Basic 1 way ANOVA

biomass.aov <- aov(dry.biomass ~ nitrogen, data = subset(data, microbe=="lib"))
summary(biomass.aov)


```
``` {r}

# CHLOROPHYLL

#Initial assessment of data

ggplot(data=data, aes(x=nitrogen,y=chlorophyll,color=microbe)) +
     geom_boxplot()

ggplot(data=data, aes(x=date,y=chlorophyll,color=microbe,shape=nitrogen)) +
     geom_point() #if there looks to be a trend, add the time in the lm equation 

#Welch's t-test to assess potential association between nitrogen and dry plant biomass, factoring in apo plots by dividing by the average

ttest_chloro <- t.test((libdata$chlorophyll/chloro_apos) ~ libdata$nitrogen, data=libdata, var.equal=FALSE)

#Publication-quality plot of means+/-CI for each measurement variable, including apos. Not sure about the purpose of the intercept line or if it looks how it's supposed to? 13 Feb 2023

ggplot(data=subset(plotmeans_data, microbe != "wt"), aes(x=nitrogen, y=meanchloro, color=microbe)) +
  geom_point(size=3) +
  geom_errorbar(aes(ymin=meanchloro-CIchloro, ymax=meanchloro+CIchloro), width=0.3) +
    ylab(expression(atop("Chlorophyll content",paste("(mean \U00B1 95% CI, n = 5)")))) +
  geom_hline(yintercept=1,linetype=2) +
  scale_y_continuous(limits=c(0,70),breaks=seq(0,70,by=10))+
  theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

#Linear model for residuals
chlorophyll = lm(chlorophyll ~ nitrogen + date,data=subset(data,microbe=="lib"))
# chlorophyll = lm(log10(chlorophyll) ~ nitrogen,data=data)

summary(chlorophyll)
AIC(chlorophyll)

#assess normality of residuals
chlorophyll_res = residuals(chlorophyll)
summary(chlorophyll_res) #mean and median are close
qqPlot(chlorophyll_res) #falls within 95% CI
hist(chlorophyll_res) #unimodal and fairly gaussian looking
boxplot(chlorophyll_res) #fairly even spread of data
shapiro.test(chlorophyll_res) #not significant
#All looks okay

#assess homoscedasticity of residuals
plot(fitted(chlorophyll),chlorophyll_res);
abline(h=0,lty=2);
lines(smooth.spline(fitted(chlorophyll),chlorophyll_res)); #fairly even spread
leveneTest(chlorophyll_res ~ nitrogen , data = subset(data,microbe=="lib")) #not significant
#All looks okay

#omnibus test
Anova(chlorophyll)

#Basic 1 way ANOVA

chloro.aov <- aov(chlorophyll ~ nitrogen, data = subset(data, microbe=="lib"))
summary(chloro.aov)


```

``` {r}

# LEAF COUNT

#Initial assessment of data
ggplot(data=data, aes(x=nitrogen,y=leaves,color=microbe)) +
     geom_boxplot()

ggplot(data=data, aes(x=date,y=leaves,color=microbe,shape=nitrogen)) +
     geom_point() 

#Welch's t-test to assess potential association between nitrogen and dry plant biomass, factoring in apo plots by dividing by the average

ttest_leaves <- t.test((libdata$leaves/leaves_apos) ~ libdata$nitrogen, data=libdata, var.equal=FALSE)

#Plot of means+/-CI for each measurement variable, including apos. Not sure about the purpose of the intercept line or if it looks how it's supposed to? 13 Feb 2023

ggplot(data=subset(plotmeans_data, microbe != "wt"), aes(x=nitrogen, y=meanleaves, color=microbe)) +
  geom_point(size=3) +
  geom_errorbar(aes(ymin=meanleaves-CIleaves, ymax=meanleaves+CIleaves), width=0.3) +
  geom_hline(yintercept=1,linetype=2) +
  ylab(expression(atop("Leaf count",paste("(mean \U00B1 95% CI, n = 5)")))) +
  geom_hline(yintercept=1,linetype=2) +
  scale_y_continuous(limits=c(0,400),breaks=seq(0,400,by=50))+
    theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

#Linear model for residuals
leafcount = lm(leaves ~ nitrogen + date,data=subset(data, microbe=="lib"))
# biomass = lm(log10(librarymass$nodule.biomass) ~ nitrogen,data=librarymass)

summary(leafcount)
AIC(leafcount)

#assess normality of residuals
leafcount_res = residuals(leafcount)
summary(leafcount_res) #mean and median are close
qqPlot(leafcount_res) #falls within 95% CI
hist(leafcount_res) #unimodal and fairly gaussian looking
boxplot(leafcount_res) #fairly even spread of data
shapiro.test(leafcount_res) #not significant
#All looks okay

#assess homoscedasticity of residuals
plot(fitted(leafcount),leafcount_res);
abline(h=0,lty=2);
lines(smooth.spline(fitted(leafcount),leafcount_res)); #fairly even spread
leveneTest(leafcount_res ~ nitrogen, data = subset(data,microbe=="lib")) #not significant
#All looks okay

#omnibus test
Anova(leafcount)

#Basic 1 way ANOVA

leaf.aov <- aov(leaves ~ nitrogen, data = subset(data, microbe=="lib"))
summary(leaf.aov)


```


``` {r}

# HEIGHT

#Initial assessment of data

ggplot(data=data %>% dplyr::filter(microbe != "pbs"), aes(x=nitrogen,y=height)) +
     geom_boxplot()

ggplot(data=data %>% dplyr::filter(microbe != "pbs"), aes(x=date,y=height)) +
     geom_point() #if there looks to be a trend, add the time in the lm equation

#Welch's t-test to assess potential association between nitrogen and dry plant biomass, factoring in apo plots by dividing by the average

ttest_height <- t.test((libdata$height/height_apos) ~ libdata$nitrogen, data=libdata, var.equal=FALSE)

#Plot of means+/-CI for each measurement variable, including apos. Not sure about the purpose of the intercept line or if it looks how it's supposed to? 13 Feb 2023

ggplot(data=subset(plotmeans_data, microbe != "wt"), aes(x=nitrogen, y=meanheight, color=microbe)) +
  geom_point(size=3) +
  geom_errorbar(aes(ymin=meanheight-CIheight, ymax=meanheight+CIheight),width=0.3) +
  geom_hline(yintercept=1,linetype=2) +
   ylab(expression(atop("Plant height [cm]",paste("(mean \U00B1 95% CI, n = 5)")))) +
  geom_hline(yintercept=1,linetype=2) +
  scale_y_continuous(limits=c(0,70),breaks=seq(0,70,by=10))+
    theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

#Linear model for residuals
height = lm(height ~ nitrogen + date,data=subset(data,microbe=="lib"))
# height = lm(log10(height) ~ nitrogen,data=data)

summary(height)
AIC(height)

#assess normality of residuals
height_res = residuals(height)
summary(height_res) #mean and median are close
qqPlot(height_res) #falls within 95% CI
hist(height_res) #unimodal and fairly gaussian looking
boxplot(height_res) #fairly even spread of data
shapiro.test(height_res) #not significant
#All looks okay

#assess homoscedasticity of residuals
plot(fitted(height),height_res);
abline(h=0,lty=2);
lines(smooth.spline(fitted(height),height_res)); #fairly even spread
leveneTest(height_res ~ nitrogen, data = subset(data,microbe=="lib")) #not significant
#All looks okay

#omnibus test
Anova(height)

#Basic 1 way ANOVA

height.aov <- aov(height ~ nitrogen, data = subset(data, microbe=="lib"))
summary(height.aov)


```

