---
title: "Plant data analysis RB-TnSeq"
author: "Caleb Hill, John McMullen, Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: inline
---

## Clear workspace and set directory
```{r}
rm(list=ls())
getwd()
# will need to update following line to map to your files
 setwd("C:/Users/User/Desktop/thesis_stuff/R_working")

## Load packages and functions

# these are packages that you might need for data wrangling, etc.
require("png")
require("dplyr")
require("grid")
require("ggplot2")
require("qqplotr")
library("car")
library("tidyverse")

# these are functions for summary statistics
#LL.95 <- function(x) t.test(x)$conf.int[1]
#UL.95 <- function(x) t.test(x)$conf.int[2]
#sem <- function(x) sqrt(var(x)/length(x))
#cv <- function(x) sd(x)/sqrt(mean(x))
 
CI <- function(x)
  1.96*sd(x)/sqrt(length(x)) #returns the value which is added/subtracted from the mean to yield the CI

# load data

data <- read.csv("rhizobia.plant.csv")

## Convert to factor/date variable

data$microbe<-as.factor(data$microbe)
data$plant<-as.factor(data$plant)
data$nitrogen<-as.factor(data$nitrogen)
data$date<-as.Date(data$date, format = "%m/%d/%Y")

st.date = as.Date("7/13/2022",format="%m/%d/%Y")

data$date <- data$date-st.date #convert to days post inoculation

data$date <- as.numeric(as.character(gsub(" days",replacement = "",x=data$date)))

```

``` {r}

#BIOMASS

#Initial assessment of data

library(dplyr)

ggplot(data=data, aes(x=nitrogen,y=dry.biomass,color=microbe)) +
     geom_boxplot()

ggplot(data=data, aes(x=date,y=dry.biomass,color=microbe,shape=nitrogen)) +
     geom_point() #if there looks to be a trend, add the time in the lm equation #filter functions remove PBs negative controls from dataset; can be further altered to look only at lib data rather than lib+WT

#Assess the effect of rhizobia presence over time points, factoring in aposymbiotic plots by dividing by the average
```

``` {r}

# t tests comparing height, chlorophyll, leaf count, dry biomass for +N vs ambient conditions

libdata <- data %>% filter(microbe=="lib")

apos <- data %>% filter(microbe=="pbs")

height_apos <- mean(apos$height)

chloro_apos <- mean(apos$chlorophyll)

leaves_apos <- mean(apos$leaves)

biomass_apos <- mean(apos$dry.biomass)

#aposymbiotic means used in ttest model

ttest_height <- t.test((libdata$height/height_apos) ~ libdata$nitrogen, data=libdata, var.equal=FALSE)

ttest_chloro <- t.test((libdata$chlorophyll/chloro_apos) ~ libdata$nitrogen, data=libdata, var.equal=FALSE)

ttest_leaves <- t.test((libdata$leaves/leaves_apos) ~ libdata$nitrogen, data=libdata, var.equal=FALSE)

ttest_mass <- t.test((libdata$dry.biomass/biomass_apos) ~ libdata$nitrogen, data=libdata, var.equal=FALSE)

#WElch's t-tests for each plant variable

plotmeans_data <- data %>% group_by(microbe, nitrogen) %>% summarise(meanheight=mean(height), CIheight=CI(height), meanchloro=mean(chlorophyll), CIchloro=CI(chlorophyll), meanleaves=mean(leaves), CIleaves=CI(leaves), meanbiomass=mean(dry.biomass), CIbiomass=CI(dry.biomass)) #creates dataframe showing means for all treatment groups

#plot of averages per treatment group with 95% confidence intervals

ggplot(data=subset(plotmeans_data, microbe != "wt"), aes(x=nitrogen, y=meanheight, color=microbe)) +
  geom_point() +
  geom_errorbar(aes(ymin=meanheight-CIheight, ymax=meanheight+CIheight)) +
  geom_hline(yintercept=1,linetype=2)

ggplot(data=subset(plotmeans_data, microbe != "wt"), aes(x=nitrogen, y=meanchloro, color=microbe)) +
  geom_point() +
  geom_errorbar(aes(ymin=meanchloro-CIchloro, ymax=meanchloro+CIchloro)) +
  geom_hline(yintercept=1,linetype=2)

ggplot(data=subset(plotmeans_data, microbe != "wt"), aes(x=nitrogen, y=meanleaves, color=microbe)) +
  geom_point() +
  geom_errorbar(aes(ymin=meanleaves-CIleaves, ymax=meanleaves+CIleaves)) +
  geom_hline(yintercept=1,linetype=2)

ggplot(data=subset(plotmeans_data, microbe != "wt"), aes(x=nitrogen, y=meanbiomass, color=microbe)) +
  geom_point() +
  geom_errorbar(aes(ymin=meanbiomass-CIbiomass, ymax=meanbiomass+CIbiomass)) +
  geom_hline(yintercept=1,linetype=2)

#not sure about the purpose of the intercept line or if it looks how it's supposed to? 10 feb 2023

``` 


``` {r}

# 10 Feb 2023: in the process of rewriting some of the analyses, keeping these chunks around for now


# BIOMASS

biomass = lm(dry.biomass ~ nitrogen,data=subset(data,microbe=="lib"))
# biomass = lm(log10(dry.biomass) ~ nitrogen,data=data)

summary(biomass)
AIC(biomass)

#assess normality of residuals
biomass_res = residuals(biomass)
summary(biomass_res) #mean and median are close
qqPlot(biomass_res) #falls within 95% CI
hist(biomass_res) #unimodal and fairly gaussian looking
boxplot(biomass_res) #fairly even spread of data
shapiro.test(biomass_res) #not significant
#All looks okay

#assess homoscedasticity of residuals
plot(fitted(biomass),biomass_res);
abline(h=0,lty=2);
#lines(smooth.spline(fitted(biomass),biomass_res)); #fairly even spread
leveneTest(biomass_res ~ nitrogen, data = subset(data,microbe=='lib')) #not significant
#All looks okay

#omnibus test
Anova(biomass)


#############################

#create a SE function
se <- function(x) {sd(x)/sqrt(length(x))}

#setup data to plot
biomass_plot <- data %>%
     filter(microbe=="lib") %>%
     group_by(nitrogen) %>% 
     summarise(mean = mean(dry.biomass), SE=se(dry.biomass))


#Publication quality figure

ggplot(biomass_plot, aes(x=nitrogen,y=mean)) +
  geom_point(size=5)+
  geom_errorbar(aes(ymin=mean-SE,ymax=mean+SE),width=0.3) +
  ylab(expression(atop("Biomass [g]",paste("(mean \U00B1 SE, n = 5)")))) +
  #scale_y_continuous(limits=c(0.85,4),breaks=seq(1,4,by=1))+
  theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

# figure still needs work for formatting stuff as of 2/03/2023
        
```

``` {r}

#CHLOROPHYLL

#Initial assessment of data

library(dplyr)

ggplot(data=data, aes(x=nitrogen,y=chlorophyll,color=microbe)) +
     geom_boxplot()

ggplot(data=data, aes(x=date,y=chlorophyll,color=microbe,shape=nitrogen)) +
     geom_point() #if there looks to be a trend, add the time in the lm equation #filter functions remove PBs negative controls from dataset; can be further altered to look only at lib data rather than lib+WT

#Assess the effect of rhizobia presence over time points. Due to variation in magnitude of plant biomass, data was log10 transformed. I'd check without log10 first and see how the residuals look.

chlorophyll = lm(chlorophyll ~ nitrogen,data=subset(data,microbe=="lib"))
# chlorophyll = lm(log10(chlorophyll) ~ nitrogen,data=data)

summary(chlorophyll)
AIC(chlorophyll)

#assess normality of residuals
chlorophyll_res = residuals(chlorophyll)
summary(chlorophyll_res) #mean and median are close
qqPlot(chlorophyll_res) #falls within 95% CI
hist(chlorophyll_res) #unimodal and fairly gaussian looking
boxplot(chlorophyll_res) #fairly even spread of data
shapiro.test(chlorophyll_res) #not significant
#All looks okay

#assess homoscedasticity of residuals
plot(fitted(chlorophyll),chlorophyll_res);
abline(h=0,lty=2);
lines(smooth.spline(fitted(chlorophyll),chlorophyll_res)); #fairly even spread
leveneTest(chlorophyll_res ~ nitrogen , data = subset(data,microbe=="lib")) #not significant
#All looks okay

#omnibus test
Anova(chlorophyll)


#############################

#create a SE function
se <- function(x) {sd(x)/sqrt(length(x))}

#setup data to plot
chlorophyll_plot <- data %>%
     filter(microbe=="lib")%>%
     group_by(nitrogen) %>% 
     summarise(mean = mean(chlorophyll), SE=se(chlorophyll))


#Publication quality figure

ggplot(chlorophyll_plot, aes(x=nitrogen,y=mean)) +
  geom_point(size=5)+
  geom_errorbar(aes(ymin=mean-SE,ymax=mean+SE),width=0.3) +
  ylab(expression(atop("Chlorophyll content)",paste("(mean \U00B1 SE, n = 5)")))) +
  #scale_y_continuous(limits=c(0.85,4),breaks=seq(1,4,by=1))+
  theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

# figure still needs work for formatting stuff as of 2/03/2023
        
```

``` {r}

#NODULE WEIGHT

#Initial assessment of data

library(dplyr)

librarymass<-data %>% dplyr::filter(microbe == "lib") #nod biomass was only collected for the library

ggplot(data=librarymass, aes(x=nitrogen,y=nodule.biomass)) +
     geom_boxplot()

ggplot(data=librarymass, aes(x=date,y=nodule.biomass)) +
     geom_point() #if there looks to be a trend, add the time in the lm equation 

#Assess the effect of rhizobia presence over time points. Due to variation in magnitude of plant biomass, data was log10 transformed. I'd check without log10 first and see how the residuals look.

nodbiomass = lm(nodule.biomass ~ nitrogen,data=librarymass)
# biomass = lm(log10(librarymass$nodule.biomass) ~ nitrogen,data=librarymass)

summary(nodbiomass)
AIC(nodbiomass)

#assess normality of residuals
nodbiomass_res = residuals(nodbiomass)
summary(nodbiomass_res) #mean and median are close
qqPlot(nodbiomass_res) #falls within 95% CI
hist(nodbiomass_res) #unimodal and fairly gaussian looking
boxplot(nodbiomass_res) #fairly even spread of data
shapiro.test(nodbiomass_res) #not significant
#All looks okay

#assess homoscedasticity of residuals
plot(fitted(nodbiomass),nodbiomass_res);
abline(h=0,lty=2);
lines(smooth.spline(fitted(nodbiomass),nodbiomass_res)); #fairly even spread
leveneTest(nodbiomass_res ~ nitrogen * date, data = librarymass) #not significant
#All looks okay

#omnibus test
Anova(nodbiomass)


#############################

#create a SE function
se <- function(x) {sd(x)/sqrt(length(x))}

#setup data to plot
nodbiomass_plot <- data %>%
     filter(microbe=="lib") %>%
     group_by(nitrogen) %>% 
     summarise(mean = mean(nodule.biomass), SE=se(nodule.biomass))


#Publication quality figure

ggplot(nodbiomass_plot, aes(x=nitrogen,y=mean)) +
  geom_point(size=5)+
  geom_errorbar(aes(ymin=mean-SE,ymax=mean+SE),width=0.3) +
  ylab(expression(atop(~Log[10]~"(nodule biomass [mg])",paste("(mean \U00B1 SE, n = 5)")))) +
  #scale_y_continuous(limits=c(0.85,4),breaks=seq(1,4,by=1))+
  theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

# figure still needs work for formatting stuff as of 2/03/2023
        
```

``` {r}

#HEIGHT

#Initial assessment of data

library(dplyr)

ggplot(data=data %>% dplyr::filter(microbe != "pbs"), aes(x=nitrogen,y=height)) +
     geom_boxplot()

ggplot(data=data %>% dplyr::filter(microbe != "pbs"), aes(x=date,y=height)) +
     geom_point() #if there looks to be a trend, add the time in the lm equation #filter functions remove PBs negative controls from dataset; can be further altered to look only at lib data rather than lib+WT

#Assess the effect of rhizobia presence over time points. Due to variation in magnitude of plant biomass, data was log10 transformed. I'd check without log10 first and see how the residuals look.

height = lm(height ~ nitrogen ,data=subset(data,microbe=="lib"))
# height = lm(log10(height) ~ nitrogen,data=data)

summary(height)
AIC(height)

#assess normality of residuals
height_res = residuals(height)
summary(height_res) #mean and median are close
qqPlot(height_res) #falls within 95% CI
hist(height_res) #unimodal and fairly gaussian looking
boxplot(height_res) #fairly even spread of data
shapiro.test(height_res) #not significant
#All looks okay

#assess homoscedasticity of residuals
plot(fitted(height),height_res);
abline(h=0,lty=2);
lines(smooth.spline(fitted(height),height_res)); #fairly even spread
leveneTest(height_res ~ nitrogen * date, data = data) #not significant
#All looks okay

#omnibus test
Anova(height)


#############################

#create a SE function
se <- function(x) {sd(x)/sqrt(length(x))}

#setup data to plot
height_plot <- data %>%
     filter(microbe=="lib") %>%
     group_by(nitrogen) %>% 
     summarise(mean = mean(height), SE=se(height))


#Publication quality figure

ggplot(height_plot, aes(x=nitrogen,y=mean)) +
  geom_point(size=5)+
  geom_errorbar(aes(ymin=mean-SE,ymax=mean+SE),width=0.3) +
  ylab(expression(atop("Height [cm]",paste("(mean \U00B1 SE, n = 5)")))) +
  #scale_y_continuous(limits=c(0.85,4),breaks=seq(1,4,by=1))+
  theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(linewidth = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9),angle=45,h=1),
        axis.text.y=element_text(size=rel(0.9)),
        axis.title.x = element_blank())

# figure still needs work for formatting stuff as of 2/03/2023
        
```

