---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Chunk 1: Data wrangling}

fitdat = read.delim("C:/Users/User/Desktop/thesis_stuff/R_working/fitness_data/html/SmeliPlant/fit_logratios_clean.tab", row.names = 1)
#fitdat = read.delim("~/GitHub/rhizo.rb.tnseq/Data/fitness_data/html/SmeliPlant/fit_logratios.tab", row.names = 1)
goodfitdat <- fitdat[, c("X21", "X22", "X24", "X26", "X27", "X28", "X29", "X30", "X32", "X33", "X35", "X37", "X40", "X41", "X42", "X43", "X44", "X45")]
#FITNESS SCORE data--negative log2 ratios of endpoint/starting counts

cleanrbdat = t(read.delim("C:/Users/User/Desktop/thesis_stuff/R_working/fitness_data/html/SmeliPlant/gene_counts_clean.tab", row.names = 1))
#cleanrbdat = t(read.delim("~/GitHub/rhizo.rb.tnseq/Data/fitness_data/html/SmeliPlant/gene_counts_clean.tab", row.names = 1))
goodcountdat <- subset(cleanrbdat, colnames(fitdat) %in% c("X21", "X22", "X24", "X26", "X27", "X28", "X29", "X30", "X32", "X33", "X35", "X37", "X40", "X41", "X42", "X43", "X44", "X45"))
#COUNTS DATA for analyses that can't use log ratio data for whatever reason (negative numbers in data, log scale, etc)

newcountnames <- substr(colnames(goodcountdat), 0, 9)
colnames(goodcountdat) <- newcountnames #removes description from column names, leaving only locus id

truecountnames <- grep("^SMa", colnames(goodcountdat))
colnames(goodcountdat)[truecountnames] <- substr(colnames(goodcountdat)[truecountnames], 0, 7) #removes trailing characters from SMa ids
finalcountnames <- grep("^SMc", colnames(goodcountdat))
colnames(goodcountdat)[finalcountnames] <- gsub("\\s+$", "", colnames(goodcountdat)[finalcountnames]) #ditto for SMc ids

cleanrbdat <- as.data.frame(cleanrbdat)

rownames(cleanrbdat) <- cleanrbdat$comb
cleanrbdat = t(cleanrbdat[,-c(1:4)])
metadata = as.data.frame(matrix(ncol=2,nrow=21))
metadata[,1] <-c(rep("nod",9),rep("bact",7),rep("start",5))
metadata[,2] <-c(rep("fertilized",4),rep("ambient",5),rep("fertilized",4),rep("ambient",3),rep("time0",5))
colnames(metadata) <- c("compartment","Ntreatment")  #this cleans up and labels data by treatment/compartment

labeled_metadata <- metadata
row.names(labeled_metadata) <- c("X21", "X22", "X23", "X24", "X26", "X27", "X28", "X29", "X30", "X31", "X32", "X33", "X35", "X37", "X39", "X40", "X41", "X42", "X43", "X44", "X45") #adds numerical IDs to metadata df

goodqual_metadata <- subset(labeled_metadata, row.names(labeled_metadata) %in% c("X21", "X22", "X24", "X26", "X27", "X28", "X29", "X30", "X32", "X33", "X35", "X37", "X40", "X41", "X42", "X43", "X44", "X45"))
potlabels <- c("1_nf", "2_nf", "4_nf", "6_na", "7_na", "8_na", "9_na", "10_na", "2_bf", "3_bf", "5_bf", "7_ba", "10_ba", "t0_1", "t0_2", "t0_3", "t0_4", "t0_5") 
goodqual_metadata$newID <- potlabels #adds abbreviated treatment/compartment id to the pot numbers

finalmetadata <- subset(goodqual_metadata, row.names(goodqual_metadata) %in% c("X21", "X22", "X24", "X26", "X27", "X28", "X29", "X30", "X32", "X33", "X35", "X37", "X40")) #filters out t0

library(vegan)
library(ggplot2)
library(stringr)
library(tidyverse)
library(dplyr)
library(tidyr)
library(reshape2)
library(tibble)
require("psych")

```

```{r Chunk 2: Alpha diversity}

shannonfit <- numeric(nrow(goodcountdat))
for(j in 1:nrow(goodcountdat)) {
  shannonfit[j] <- vegan::diversity(goodcountdat[j,], index = "shannon")
}

shannonfit #SHANNON DIVERSITY of lib

Evar <- function(x) {
  x <- as.vector(x[x > 0])
  1 - (2/pi)*atan(var(log(x)))
} #function calculating SMITH AND WILSON'S EVENNESS INDEX for the given site

Evarfit <- numeric(nrow(goodcountdat))
for(j in 1:nrow(goodcountdat)) {
  Evarfit[j] <- Evar(goodcountdat[j,])
}

Evarfit #S&W EVENNESS of lib in each pot

countzeros <- function(row) {
  numzeros <- sum(row == 0)
  percentzeros <- 100 - (numzeros / length(row) * 100)
  return(percentzeros)
} #function which returns the % OF SPECIES FOUND in each site

percentfoundfit <- apply(goodcountdat, 1, countzeros) #calculates % found for each row (site)
percentfoundfit

S_obs <- function(x = ""){
  rowSums(x>0)*1
} #function which returns OBSERVED SPECIES RICHNESS in a given site

richnessfit <-  S_obs(goodcountdat)

richnessfit #SPECIES (ie, gene/deletion mutant) RICHNESS

alphadiversitylib = as.data.frame(matrix(ncol=4,nrow=nrow(goodcountdat)))
colnames(alphadiversitylib) <- c('Shannon diversity','Evenness (SW)','% Found','Richness')
rownames(alphadiversitylib) <- rownames(goodcountdat)
alphadiversitylib[,1] <- shannonfit
alphadiversitylib[,2] <- Evarfit
alphadiversitylib[,3] <- percentfoundfit
alphadiversitylib[,4] <- richnessfit
alphadiversitylib #final collated dataframe of alpha diversity measures by pot

```

```{r Chunk 3: Resemblance matrices}

fitmetadata <- read.csv("C:/Users/User/Desktop/analyze_Nfitness/smeliplant_neutral_cog_clean.csv")
#fitmetadata <- read.csv("~/Github/rhizo.rb.tnseq/Scripts/reciprocal_BLAST_essentiality/rbh_essentiality_supplies/smeliplant_neutral_cog_clean.csv")
#metadata describing genes in detail--locus id, name, cog category, description, essentiality for nodulation, etc etc

fitmetadata <- fitmetadata[, -c(8:11)] #clean up empty columns
fitmetadata <- fitmetadata[, -c(1)] #same here

newnamesfitrel <- substr(row.names(goodfitdat), 0, 9) 
newnamesfitrel
row.names(goodfitdat) <- newnamesfitrel #remove description info from labels

truenames <- grep("^SMa", row.names(goodfitdat)) 
row.names(goodfitdat)[truenames] <- substr(row.names(goodfitdat)[truenames], 0, 7) #remove trailing space and letter from SMa names

truefitnames <- grep("^SMc", row.names(goodfitdat)) 
row.names(goodfitdat)[truefitnames] <- gsub("\\s+$", "", row.names(goodfitdat)[truefitnames])  #remove trailing space from SMc names

completefit <- merge(fitmetadata, goodfitdat, by.x = 1, by.y = 0)
nodESfit <- subset(completefit, essentiality=="essential")
nodNEfit <- subset(completefit, essentiality=="N") #fitness data subsetted into groups of interest

#to subset N metabolism genes, a blastKOALA annotation was conducted and N metabolism genes pulled from the KEGG reconstruction
nitrogengenes <- read.delim("C:/Users/User/Desktop/blastkoala_annotation_smeli.txt", header=FALSE)
#nitrogengenes <- read.delim("~/Github/rhizo.rb.tnseq/Data/fitness_data/html/SmeliPlant/blastkoala_annotation_smeli.txt", header=FALSE)

nitrogengenes$V1 <- substr(nitrogengenes$V1, 7, 15)
Nnames <- grep("^SMa", nitrogengenes$V1)
nitrogengenes$V1[Nnames] <- substr((nitrogengenes$V1)[Nnames], 0, 7)
nitronames <- grep("^SMc", nitrogengenes$V1) 
nitrogengenes$V1[nitronames] <- gsub("\\s+$", "", nitrogengenes$V1[nitronames]) #same name-cleaning process as above

metabloci <- c("SMa0228", "SMc04028", "SMc04026", "SMa1250", "SM_b20986", "SMa1182", "SMc02150", "SMa0697", "SMc04083", "SMa0045", "SMc02613", "SMc00762", "SMc00948", "SMc01594", "SMc01973", "SMc02352", "SM_b20745", "SMa1276", "SMa1236", "SMa1233", "SM_b20436", "SMa0827", "SMa0825", "SMa0829", "SMa1273", "SMc04085", "SMa0585", "SMa0583", "SMa0581", "SM_b20985", "SM_b20984") #from Nmetabolismlist.txt, which is sourced from blastKOALA
Nmetabolism <- subset(nitrogengenes, V1 %in% metabloci)
Nmetabolismfit <- subset(completefit, completefit$locus_tag %in% Nmetabolism$V1) #N metabolism fitness subset

fitmetadata <- fitmetadata[, -c(8:11)]

nodESfit <- nodESfit[, -c(2:6)]
nodNEfit <- nodNEfit[, -c(2:6)]
completefit <- completefit[, -c(2:6)]
Nmetabolismfit <- Nmetabolismfit[, -c(2:6)] #removes metadata from subsetted groups to get only the numerical data in the frame itself

row.names(nodESfit) <- nodESfit[,1]
nodESfit <- nodESfit[, -c(1)]
row.names(nodNEfit) <- nodNEfit[,1]
nodNEfit <- nodNEfit[, -c(1)]
row.names(completefit) <- completefit[,1]
completefit <- completefit[, -c(1)]
row.names(Nmetabolismfit) <- Nmetabolismfit[,1]
Nmetabolismfit <- Nmetabolismfit[, -c(1)] #updates names and deletes extra row

nodESfit <- t(nodESfit)
nodNEfit <- t(nodNEfit)
completefit <- t(completefit)
Nmetabolismfit <- t(Nmetabolismfit) #need to be flipped to this orientation for cluster diagrams etc

row.names(nodESfit) <- potlabels
row.names(nodNEfit) <- potlabels
row.names(completefit) <- potlabels
row.names(Nmetabolismfit) <- potlabels #relabel pots to include pot number and treatment/compartment info all in one

dissim_nodES <- vegdist(nodESfit, method = "euclid", diag = FALSE)
dissim_nodNE <- vegdist(nodNEfit, method = "euclid", diag = FALSE)
dissim_complete <- vegdist(completefit, method = "euclid", diag = FALSE)
dissim_Nmetabolism <- vegdist(Nmetabolismfit, method = "euclid", diag = FALSE) #resemblance matrices; still experimenting with different dissimilarity indices. Fitness data is log ratio data so it's kind of weird; might need to design one

scaled_nodES <- scale(nodESfit)
scaled_nodNE <- scale(nodNEfit)
scaled_complete <- scale(completefit)
scaled_Nmetabolism <-scale(Nmetabolismfit) #autoscaled matrices for kmo/bartlett tests (need to be scaled before making final cor matrices for tests)

cor_nodES <- cor(scaled_nodES)
cor_nodNE <- cor(scaled_nodNE)
cor_complete <- cor(scaled_complete)
cor_Nmetabolism <- cor(scaled_Nmetabolism) #correlation matrices for downstream statistical analyses

finalscaled_nodES <- as.data.frame(scaled_nodES[1:(nrow(scaled_nodES) - 5),])
finalscaled_nodNE <- as.data.frame(scaled_nodNE[1:(nrow(scaled_nodNE) - 5),])
finalscaled_complete <- as.data.frame(scaled_complete[1:(nrow(scaled_complete) - 5),])
finalscaled_Nmetabolism <- as.data.frame(scaled_Nmetabolism[1:(nrow(scaled_Nmetabolism) - 5),]) #scaled matrices without t0 for permanova, PCA, etc

```

```{r Chunk 4: PERMANOVA}

nodES_permanova <- adonis2(finalscaled_nodES ~ finalmetadata$Ntreatment/finalmetadata$compartment, data = finalscaled_nodES, method="euclidean")

nodNE_permanova <- adonis2(finalscaled_nodNE ~ finalmetadata$Ntreatment/finalmetadata$compartment, data = finalscaled_nodNE, method="euclidean")

complete_permanova <- adonis2(finalscaled_complete ~ finalmetadata$Ntreatment/finalmetadata$compartment, data = finalscaled_complete, method="euclidean")

Nmetabolism_permanova <- adonis2(finalscaled_Nmetabolism ~ finalmetadata$Ntreatment/finalmetadata$compartment, data = finalscaled_Nmetabolism, method="euclidean")

#need to think about the architecture of this a little more--ideally, we would stratify by pot, but this isn't feasible with the bacteroid and nodule data split across the pots like this (nodule data from pots 1, 2, 4, 6, 7, 8, 9, 10; bacteroid data from pots 2, 3, 5, 7, 10)
```

```{r Chunk 5: Ward's clustering}

# Ordination plot is in progress, but I wanted some quick and easy plots

ward_nodES <- hclust(dissim_nodES, method = "ward.D2")
ward_nodNE <- hclust(dissim_nodNE, method = "ward.D2")
ward_complete <- hclust(dissim_complete, method = "ward.D2") 
ward_Nmetabolism <- hclust(dissim_Nmetabolism, method = "ward.D2")

wardlabels <- paste(goodqual_metadata$compartment, goodqual_metadata$Ntreatment, sep = "_")
wardlabels <- as.data.frame(wardlabels)
row.names(wardlabels) <- row.names(goodqual_metadata)
wardlabels$potID <- c("pot1_", "pot2_", "pot4_", "pot6_", "pot7_", "pot8_", "pot9_", "pot10_", "pot2_", "pot3_", "pot5_", "pot7_", "pot10_", "1_", "2_", "3_", "4_", "5_")
wardlabels <- paste(wardlabels$potID, wardlabels$wardlabels, sep = "")


par(mar = c(1, 5, 2, 2) + 0.1)
plot(ward_nodES, main = "Ward's Clustering of sites by essential nodulation gene fitness", ylab = "Squared Euclidean Distance", labels = wardlabels)
plot(ward_nodNE, main = "Ward's Clustering of sites by nonessential nodulation gene fitness", ylab = "Squared Euclidean Distance", labels = wardlabels)
plot(ward_complete, main = "Ward's Clustering of sites by whole-genome fitness", ylab = "Squared Euclidean Distance", labels = wardlabels) 
plot(ward_Nmetabolism, main = "Ward's Clustering of sites by N metabolism gene fitness", ylab = "Squared Euclidean Distance", labels = wardlabels)


``` 

```{r Chunk 6: RACs, K-S tests, rank-abundance plots}

RAC <- function(x = ""){
  x = as.vector(x)
  x.ab = x[x > 0]
  x.ab.ranked = x.ab[order(x.ab, decreasing = TRUE)]
  return(x.ab.ranked)
} #returns a rank-abundance dataset for a given site to be plotted

RACmetadata <- metadata
row.names(RACmetadata) <- c("021", "022", "023", "024", "026", "027", "028", "029", "030", "031", "032", "033", "035", "037", "039", "040", "041", "042", "043", "044", "045")
RACmetadata <- subset(RACmetadata, row.names(RACmetadata) %in% c("021", "022", "024", "026", "027", "028", "029", "030", "032", "033", "035", "037", "040", "041", "042", "043", "044", "045"))
row.names(goodcountdat) <- c("021", "022", "024", "026", "027", "028", "029", "030", "032", "033", "035", "037", "040", "041", "042", "043", "044", "045")
#above block sets up row names and such to be merged and unmerged

RACsubsetter <- as.data.frame(cbind(goodcountdat, RACmetadata))
RACsubsetter <- RACsubsetter %>% mutate(group = paste(compartment, Ntreatment, sep = "_"))
RACsubsetter <- RACsubsetter[, -c(5176:5177)] #merges metadata tags into a single unique treatment group ID

RACsubsetter <- RACsubsetter %>%
  mutate(across(1:5175, as.numeric)) #changes data to numeric

RACdata <- RACsubsetter %>%
  group_by(group) %>%
  summarise(across(starts_with("SM"), mean)) #averages each treatment together and produces a table listing mean counts

RACdata <- as.data.frame(RACdata)
row.names(RACdata) <- RACdata[,1]
RACdata <- RACdata[,-1] #cleans up dataframe so it can be unlisted and plotted

colnames(RACdata) <- substr(colnames(RACdata), 0, 9)
RACnames <- grep("^SMa", colnames(RACdata))
colnames(RACdata)[RACnames] <- substr((colnames(RACdata))[RACnames], 0, 7)
trueRACnames <- grep("^SMc", colnames(RACdata)) 
colnames(RACdata)[trueRACnames] <- gsub("\\s+$", "", colnames(RACdata)[trueRACnames]) #ensures column names are exactly the same as the ones in Nmetabolism for matching genes of interest

RACdata_Nmetabolism <- RACdata[, intersect(colnames(RACdata), Nmetabolism$V1)] #similar code from elsewhere wasn't working, so I asked chatGPT to suggest a new method and it gave me the intersect() syntax within this

RACdata_nodNE <- RACdata[, intersect(colnames(RACdata), colnames(nodNEfit))]
RACdata_nodES <- RACdata[, intersect(colnames(RACdata), colnames(nodESfit))]

#RACs for whole genomes
bactambRAC <- unlist(RACdata[1,])
bactfertRAC <- unlist(RACdata[2,])
nodambRAC <- unlist(RACdata[3,])
nodfertRAC <- unlist(RACdata[4,])
t0RAC <- unlist(RACdata[5,]) #converts rows to proper format for RAC analysis and plotting

RAC_bactamb <- RAC(bactambRAC)
RAC_bactfert <- RAC(bactfertRAC)
RAC_nodamb <- RAC(nodambRAC)
RAC_nodfert <- RAC(nodfertRAC)
RAC_t0 <- RAC(t0RAC)

#RACs for N metabolism genes
Nmetab_bactambRAC <- unlist(RACdata_Nmetabolism[1,])
Nmetab_bactfertRAC <- unlist(RACdata_Nmetabolism[2,])
Nmetab_nodambRAC <- unlist(RACdata_Nmetabolism[3,])
Nmetab_nodfertRAC <- unlist(RACdata_Nmetabolism[4,])
Nmetab_t0RAC <- unlist(RACdata_Nmetabolism[5,])

RAC_Nmetab_bactamb <- RAC(Nmetab_bactambRAC)
RAC_Nmetab_bactfert <- RAC(Nmetab_bactfertRAC)
RAC_Nmetab_nodamb <- RAC(Nmetab_nodambRAC)
RAC_Nmetab_nodfert <- RAC(Nmetab_nodfertRAC)
RAC_Nmetab_t0 <- RAC(Nmetab_t0RAC)

finalRACdata_Nmetabolism <- as.data.frame(rbind(RAC_Nmetab_bactamb, RAC_Nmetab_bactfert, RAC_Nmetab_nodamb, RAC_Nmetab_nodfert, RAC_Nmetab_t0))
colnames(finalRACdata_Nmetabolism) <- 1:29

#RACs for nodulation ES and NE genes

#NE
nodNE_bactambRAC <- unlist(RACdata_nodNE[1,])
nodNE_bactfertRAC <- unlist(RACdata_nodNE[2,])
nodNE_nodambRAC <- unlist(RACdata_nodNE[3,])
nodNE_nodfertRAC <- unlist(RACdata_nodNE[4,])
nodNE_t0RAC <- unlist(RACdata_nodNE[5,])

RAC_nodNE_bactamb <- RAC(nodNE_bactambRAC)
RAC_nodNE_bactfert <- RAC(nodNE_bactfertRAC)
RAC_nodNE_nodamb <- RAC(nodNE_nodambRAC)
RAC_nodNE_nodfert <- RAC(nodNE_nodfertRAC)
RAC_nodNE_t0 <- RAC(nodNE_t0RAC)

finalRACdata_nodNE <- as.data.frame(rbind(RAC_nodNE_bactamb, RAC_nodNE_bactfert, RAC_nodNE_nodamb, RAC_nodNE_nodfert, RAC_nodNE_t0))
colnames(finalRACdata_nodNE) <- 1:2221

#ES
nodES_bactambRAC <- unlist(RACdata_nodES[1,])
nodES_bactfertRAC <- unlist(RACdata_nodES[2,])
nodES_nodambRAC <- unlist(RACdata_nodES[3,])
nodES_nodfertRAC <- unlist(RACdata_nodES[4,])
nodES_t0RAC <- unlist(RACdata_nodES[5,])

RAC_nodES_bactamb <- RAC(nodES_bactambRAC)
RAC_nodES_bactfert <- RAC(nodES_bactfertRAC)
RAC_nodES_nodamb <- RAC(nodES_nodambRAC)
RAC_nodES_nodfert <- RAC(nodES_nodfertRAC)
RAC_nodES_t0 <- RAC(nodES_t0RAC)

finalRACdata_nodES <- as.data.frame(rbind(RAC_nodES_bactamb, RAC_nodES_bactfert, RAC_nodES_nodamb, RAC_nodES_nodfert, RAC_nodES_t0))
colnames(finalRACdata_nodES) <- 1:2756

#Kolmogorov-Smirnov tests to determine if rank-abundance curves are significantly different between treatments; WHOLE-GENOME SET

ks_bacteroid <- ks.test(RAC_bactamb, RAC_bactfert, exact = TRUE) #bacteroid treatment, -N vs +N
ks_nodule <- ks.test(RAC_nodamb, RAC_nodfert, exact = TRUE) #undiff nodule treatment, -N vs +N

ks_amb_compartment <- ks.test(RAC_nodamb, RAC_bactamb, exact = TRUE) #Bacteroid  vs undiff nodule at -N
ks_fert_compartment <- ks.test(RAC_bactfert, RAC_nodfert, exact = TRUE) #B vs undiff n at +N

#K-S N METABOLISM

ks_bacteroid_Nmetab <- ks.test(RAC_Nmetab_bactamb, RAC_Nmetab_bactfert, exact = TRUE) 
ks_nodule_Nmetab <- ks.test(RAC_Nmetab_nodamb, RAC_Nmetab_nodfert, exact = TRUE)

ks_amb_compartment_Nmetab <- ks.test(RAC_Nmetab_nodamb, RAC_Nmetab_bactamb, exact = TRUE)
ks_fert_compartment_Nmetab <- ks.test(RAC_Nmetab_bactfert, RAC_Nmetab_nodfert, exact = TRUE)

#K-S NODULATION NONESSENTIAL/ESSENTIAL

ks_bacteroid_nodNE <- ks.test(RAC_nodNE_bactamb, RAC_nodNE_bactfert, exact = TRUE) 
ks_nodule_nodNE <- ks.test(RAC_nodNE_nodamb, RAC_nodNE_nodfert, exact = TRUE)

ks_amb_nodNE <- ks.test(RAC_nodNE_nodamb, RAC_nodES_bactamb, exact = TRUE)
ks_fert_nodNE <- ks.test(RAC_nodNE_nodfert, RAC_nodNE_bactfert, exact = TRUE)

ks_bacteroid_nodES <- ks.test(RAC_nodES_bactamb, RAC_nodES_bactfert, exact = TRUE)
ks_nodule_nodES <- ks.test(RAC_nodES_nodamb, RAC_nodES_nodfert, exact = TRUE)

ks_amb_nodES <- ks.test(RAC_nodES_nodamb, RAC_nodES_bactamb, exact = TRUE)
ks_fert_nodES <- ks.test(RAC_nodES_nodfert, RAC_nodES_bactfert, exact = TRUE)

# # simple curve plots of the RACs
# 
# all_RACs <- ls(pattern = "^RAC_") #make a list with all 20 RACs
# 
# for (i in 1:length(all_RACs)) {
#   plot.new()
#   ranks <- as.vector(seq(1, length(get(all_RACs[i]))))
#   opar <- par(no.readonly = TRUE)
#   par(mar = c(5.1, 5.1, 4.1, 2.1))
#   plot(ranks, log(get(all_RACs[i])), type = 'p', axes = F,
#        xlab = "Rank in abundance", ylab = "Abundance",
#        las = 1, cex.lab = 1.4, cex.axis = 1.25)
#   
#   box()
#   axis(side = 1, labels = T, cex.axis = 1.25)
#   axis(side = 2, las = 1, cex.axis = 1.25,
#        labels = c(1, 100, 10000, 100000, 1000000), at = log(c(1, 100, 10000, 100000, 1000000)))
#   
#   mtext(all_RACs[i], side = 3, line = 1, cex = 1.5)
# } #This for loop calls the above plot code on all 20 RAC names listed within all_RACs, producing 20 rank-abundance curves
# 
# #ggplot violin plots of RAC data
# 
# for (i in 1:length(all_RACs)) {
#   
#   p <- ggplot(data.frame(x = 1:length(get(all_RACs[[i]])), 
#                           y = get(all_RACs[[i]])), 
#               aes(x = "", y = y)) +
#     geom_violin(fill = "gray", alpha = 0.8) + #violin plot
#     geom_jitter(color = "black", size = 1.5, alpha = 0.4) + #point layer
#     xlab("") +
#     ylab("Abundance") +
#     ggtitle(all_RACs[[i]]) + #title by variable name
#     theme_classic() #need to tweak theme to make it look better/cleaner
#   print(p)
# }

#example code for plotting RACs together on the same axis; the ranks need some fixing
# 
# finalRACdata_complete <- as.data.frame(rbind(RAC_bactamb, RAC_bactfert, RAC_nodamb, RAC_nodfert, RAC_t0))
# colnames(finalRACdata_complete) <- 1:5175
# finalRACdata_complete$treatment <- row.names(finalRACdata_complete)
# 
# finalRACdata_complete <- pivot_longer(finalRACdata_complete, cols = colnames(finalRACdata_complete)[1:5175])
# 
# combinedRAC_complete <- ggplot(finalRACdata_complete, aes(x = as.numeric(as.character(name)), y = log10(value), group = treatment, color = treatment, fill = treatment)) +
#   geom_line()
# 
# combinedRAC_complete

```

```{r Chunk 7: Ranked fitness, K-S, Rank-order correlation tests}

rankfit <- function(x) {
  x <- as.data.frame(x)
  x.ranked <- x[order(rownames(x)), , drop = FALSE]
  rownames(x.ranked) <- rownames(x)[order(rownames(x))]
  return(x.ranked)
} #version of the RAC function designed to rank fitness scores, which have negative and positive values
 
rankfitdata <- t(goodfitdat)
row.names(rankfitdata) <- c("021", "022", "024", "026", "027", "028", "029", "030", "032", "033", "035", "037", "040", "041", "042", "043", "044", "045")
rankfitdata <- cbind(RACsubsetter$group, rankfitdata)
rankfitdata <- as.data.frame(rankfitdata)
rankfitdata <- rankfitdata %>%
  mutate(across(2:5176, as.numeric)) #results in a properly labeled and formatted dataframe to be grouped and meaned by treatment/compartment

meanfitnessrank <- rankfitdata %>%
  group_by(V1) %>%
  summarise(across(starts_with("SM"), mean)) #table of meaned gene fitness per treatment/compartment group

meanfitnessrank <- as.data.frame(meanfitnessrank)
row.names(meanfitnessrank) <- meanfitnessrank[,1]
meanfitnessrank <- meanfitnessrank[,-1] #cleans up and relabels rows by treatment/compartment group, makes whole-genome gene fitness rank

meanfitnessrank_Nmetab <- meanfitnessrank[, intersect(colnames(meanfitnessrank), Nmetabolism$V1)]
meanfitnessrank_nodNE <- meanfitnessrank[, intersect(colnames(meanfitnessrank), colnames(nodNEfit))]
meanfitnessrank_nodES <- meanfitnessrank[, intersect(colnames(meanfitnessrank), colnames(nodESfit))] #subsets 


#fitness rankings for the whole genome
bactambrank <-unlist(meanfitnessrank[1,])
bactfertrank <- unlist(meanfitnessrank[2,])
nodambrank <- unlist(meanfitnessrank[3,])
nodfertrank <- unlist(meanfitnessrank[4,])
t0rank <- unlist(meanfitnessrank[5,])

ranked_bactamb <- rankfit(bactambrank)
ranked_bactfert <- rankfit(bactfertrank)
ranked_nodamb <- rankfit(nodambrank)
ranked_nodfert <- rankfit(nodfertrank)
ranked_t0 <- rankfit(t0rank)

#fitness rankings for the N metabolism gene set only
Nmetab_bactambrank <-unlist(meanfitnessrank_Nmetab[1,])
Nmetab_bactfertrank <- unlist(meanfitnessrank_Nmetab[2,])
Nmetab_nodambrank <- unlist(meanfitnessrank_Nmetab[3,])
Nmetab_nodfertrank <- unlist(meanfitnessrank_Nmetab[4,])
Nmetab_t0rank <- unlist(meanfitnessrank_Nmetab[5,])

ranked_Nmetab_bactamb <- rankfit(Nmetab_bactambrank)
ranked_Nmetab_bactfert <- rankfit(Nmetab_bactfertrank)
ranked_Nmetab_nodamb <- rankfit(Nmetab_nodambrank)
ranked_Nmetab_nodfert <- rankfit(Nmetab_nodfertrank)
ranked_Nmetab_t0 <- rankfit(Nmetab_t0rank)

#NE
nodNE_bactambrank <- unlist(meanfitnessrank_nodNE[1,])
nodNE_bactfertrank <- unlist(meanfitnessrank_nodNE[2,])
nodNE_nodambrank <- unlist(meanfitnessrank_nodNE[3,])
nodNE_nodfertrank <- unlist(meanfitnessrank_nodNE[4,])
nodNE_t0rank <- unlist(meanfitnessrank_nodNE[5,])

ranked_nodNE_bactamb <- rankfit(nodNE_bactambrank)
ranked_nodNE_bactfert <- rankfit(nodNE_bactfertrank)
ranked_nodNE_nodamb <- rankfit(nodNE_nodambrank)
ranked_nodNE_nodfert <- rankfit(nodNE_nodfertrank)
ranked_nodNE_t0 <- rankfit(nodNE_t0rank)

#ES
nodES_bactambrank <- unlist(meanfitnessrank_nodES[1,])
nodES_bactfertrank <- unlist(meanfitnessrank_nodES[2,])
nodES_nodambrank <- unlist(meanfitnessrank_nodES[3,])
nodES_nodfertrank <- unlist(meanfitnessrank_nodES[4,])
nodES_t0rank <- unlist(meanfitnessrank_nodES[5,])

ranked_nodES_bactamb <- rankfit(nodES_bactambrank)
ranked_nodES_bactfert <- rankfit(nodES_bactfertrank)
ranked_nodES_nodamb <- rankfit(nodES_nodambrank)
ranked_nodES_nodfert <- rankfit(nodES_nodfertrank)
ranked_nodES_t0 <- rankfit(nodES_t0rank)



#Spearman correlation tests for rankfit paired datasets

#ES
spearman_nodES_bacteroid <- cor.test(ranked_nodES_bactamb$x, ranked_nodES_bactfert$x,  method = "spearman")
spearman_nodES_nodule <- cor.test(ranked_nodES_nodamb$x, ranked_nodES_nodfert$x,  method = "spearman")
spearman_nodES_amb <- cor.test(ranked_nodES_nodamb$x, ranked_nodES_bactamb$x,  method = "spearman")
spearman_nodES_fert <- cor.test(ranked_nodES_nodfert$x, ranked_nodES_bactfert$x,  method = "spearman")

#NE
spearman_nodNE_bacteroid <- cor.test(ranked_nodNE_bactamb$x, ranked_nodNE_bactfert$x,  method = "spearman")
spearman_nodNE_nodule <- cor.test(ranked_nodNE_nodamb$x, ranked_nodNE_nodfert$x,  method = "spearman")
spearman_nodNE_amb <- cor.test(ranked_nodNE_nodamb$x, ranked_nodNE_bactamb$x,  method = "spearman")
spearman_nodNE_fert <- cor.test(ranked_nodNE_nodfert$x, ranked_nodNE_bactfert$x,  method = "spearman")

#complete
spearman_complete_bacteroid <- cor.test(ranked_bactamb$x, ranked_bactfert$x,  method = "spearman")
spearman_complete_nodule <- cor.test(ranked_nodamb$x, ranked_nodfert$x,  method = "spearman")
spearman_complete_amb <- cor.test(ranked_nodamb$x, ranked_bactamb$x,  method = "spearman")
spearman_complete_fert <- cor.test(ranked_nodfert$x, ranked_bactfert$x,  method = "spearman")

#Nmetabolism
spearman_Nmetab_bacteroid <- cor.test(ranked_Nmetab_bactamb$x, ranked_Nmetab_bactfert$x,  method = "spearman")
spearman_Nmetab_nodule <- cor.test(ranked_Nmetab_nodamb$x, ranked_Nmetab_nodfert$x,  method = "spearman")
spearman_Nmetab_amb <- cor.test(ranked_Nmetab_nodamb$x, ranked_Nmetab_bactamb$x,  method = "spearman")
spearman_Nmetab_fert <- cor.test(ranked_Nmetab_nodfert$x, ranked_Nmetab_bactfert$x,  method = "spearman")

all_spearman <- ls(pattern = "^spearman_") #list of all these htests for easy plotting with a for loop


ks_sort <- function(my_ranking) {
  sorted_list <- my_ranking[order(my_ranking, decreasing = TRUE)]
  name <- paste0("ks_", deparse(substitute(my_ranking)))
  names(sorted_list) <- name
  return(sorted_list)
} #function to re-sort fitness rankings from genome order (for spearman) to ascending order (for k-s tests)

all_ranked <- ls(pattern = "^ranked_") #gathers all the rankings together for reordering

for (name in all_ranked) {
  ranked_obj <- get(name)
  if (is.data.frame(ranked_obj)) {
    ranked_vec <- ranked_obj[, 1]
  } else {
    ranked_vec <- ranked_obj
  }
  sorted_vec <- ks_sort(ranked_vec)
  assign(paste0("ks_", name), sorted_vec)
} #for loop which calls ks_sort on all the rankings. Don't know why the redundant paste0(ks_) is needed, but it is!!

# K-S tests of ranked fitness

ks_bacteroid_fit <- ks.test(ks_ranked_bactamb, ks_ranked_bactfert, exact = TRUE)
ks_nodule_fit <- ks.test(ks_ranked_nodamb, ks_ranked_nodfert, exact = TRUE)

ks_amb_compartment_fit <- ks.test(ks_ranked_nodamb, ks_ranked_bactamb, exact = TRUE)
ks_fert_compartment_fit <- ks.test(ks_ranked_bactfert, ks_ranked_nodfert, exact = TRUE)

# K-S tests for ranked N metabolism fitness

ks_bacteroid_Nmetab_fit <- ks.test(ks_ranked_Nmetab_bactamb, ks_ranked_Nmetab_bactfert, exact = TRUE)
ks_nodule_Nmetab_fit <- ks.test(ks_ranked_Nmetab_nodamb, ks_ranked_Nmetab_nodfert, exact = TRUE)

ks_amb_compartment_Nmetab_fit <- ks.test(ks_ranked_Nmetab_nodamb, ks_ranked_Nmetab_bactamb, exact = TRUE)
ks_fert_compartment_Nmetab_fit <- ks.test(ks_ranked_Nmetab_bactfert, ks_ranked_Nmetab_nodfert, exact = TRUE)

# K-S tests for essential and nonessential nodulation gene fitness

ks_bacteroid_nodNE_fit <- ks.test(ks_ranked_nodNE_bactamb, ks_ranked_nodNE_bactfert, exact = TRUE) 
ks_nodule_nodNE_fit <- ks.test(ks_ranked_nodNE_nodamb, ks_ranked_nodNE_nodfert, exact = TRUE)

ks_amb_nodNE_fit <- ks.test(ks_ranked_nodNE_nodamb, ks_ranked_nodES_bactamb, exact = TRUE)
ks_fert_nodNE_fit <- ks.test(ks_ranked_nodNE_nodfert, ks_ranked_nodNE_bactfert, exact = TRUE)

ks_bacteroid_nodES_fit <- ks.test(ks_ranked_nodES_bactamb, ks_ranked_nodES_bactfert, exact = TRUE)
ks_nodule_nodES_fit <- ks.test(ks_ranked_nodES_nodamb, ks_ranked_nodES_nodfert, exact = TRUE)

ks_amb_nodES_fit <- ks.test(ks_ranked_nodES_nodamb, ks_ranked_nodES_bactamb, exact = TRUE)
ks_fert_nodES_fit <- ks.test(ks_ranked_nodES_nodfert, ks_ranked_nodES_bactfert, exact = TRUE)


#combined RAC-like fitness ranking plots per dataset

#ES
finalfitrank_nodES <- as.data.frame(rbind(as.numeric(ks_ranked_nodES_bactamb), as.numeric(ks_ranked_nodES_bactfert), as.numeric(ks_ranked_nodES_nodamb), as.numeric(ks_ranked_nodES_nodfert), as.numeric(ks_ranked_nodES_t0)))
colnames(finalfitrank_nodES) <- 1:2756
finalfitrank_nodES$treatment <- c("bact_amb", "bact_fert", "nod_amb", "nod_fert", "t0")

finalfitrank_nodES <- pivot_longer(finalfitrank_nodES, cols = colnames(finalfitrank_nodES)[1:2756])

combinedfitrank_nodES <- ggplot(finalfitrank_nodES, aes(x = as.numeric(as.character(name)), y = log10(value), group = treatment, color = treatment, fill = treatment)) +
  geom_line() +
  labs(title = "nodES fitness ranking")

combinedfitrank_nodES

#NE
finalfitrank_nodNE <- as.data.frame(rbind(as.numeric(ks_ranked_nodNE_bactamb), as.numeric(ks_ranked_nodNE_bactfert), as.numeric(ks_ranked_nodNE_nodamb), as.numeric(ks_ranked_nodNE_nodfert), as.numeric(ks_ranked_nodNE_t0)))
colnames(finalfitrank_nodNE) <- 1:2221
finalfitrank_nodNE$treatment <- c("bact_amb", "bact_fert", "nod_amb", "nod_fert", "t0")

finalfitrank_nodNE <- pivot_longer(finalfitrank_nodNE, cols = colnames(finalfitrank_nodNE)[1:2221])

combinedfitrank_nodNE <- ggplot(finalfitrank_nodNE, aes(x = as.numeric(as.character(name)), y = log10(value), group = treatment, color = treatment, fill = treatment)) +
  geom_line() +
  labs(title = "nodNE fitness ranking")

combinedfitrank_nodNE

#complete
finalfitrank_complete <- as.data.frame(rbind(as.numeric(ks_ranked_bactamb), as.numeric(ks_ranked_bactfert), as.numeric(ks_ranked_nodamb), as.numeric(ks_ranked_nodfert), as.numeric(ks_ranked_t0)))
colnames(finalfitrank_complete) <- 1:5175
finalfitrank_complete$treatment <- c("bact_amb", "bact_fert", "nod_amb", "nod_fert", "t0")

finalfitrank_complete <- pivot_longer(finalfitrank_complete, cols = colnames(finalfitrank_complete)[1:5175])

combinedfitrank_complete <- ggplot(finalfitrank_complete, aes(x = as.numeric(as.character(name)), y = log10(value), group = treatment, color = treatment, fill = treatment)) +
  geom_line() +
  labs(title = "Whole-genome fitness ranking")

combinedfitrank_complete

#Nmetabolism
finalfitrank_Nmetab <- as.data.frame(rbind(as.numeric(ks_ranked_Nmetab_bactamb), as.numeric(ks_ranked_Nmetab_bactfert), as.numeric(ks_ranked_Nmetab_nodamb), as.numeric(ks_ranked_Nmetab_nodfert), as.numeric(ks_ranked_Nmetab_t0)))
colnames(finalfitrank_Nmetab) <- 1:29
finalfitrank_Nmetab$treatment <- c("bact_amb", "bact_fert", "nod_amb", "nod_fert", "t0")

finalfitrank_Nmetab <- pivot_longer(finalfitrank_Nmetab, cols = colnames(finalfitrank_Nmetab)[1:29])

combinedfitrank_Nmetab <- ggplot(finalfitrank_Nmetab, aes(x = as.numeric(as.character(name)), y = log10(value), group = treatment, color = treatment, fill = treatment)) +
  geom_line() +
  labs(title = "N metabolism fitness ranking")

combinedfitrank_Nmetab


```

```{r Chunk 8: Principal component analysis + plots}

#WORK IN PROGRESS

KMO(cor_nodES)
KMO(cor_nodNE)
KMO(cor_complete)
KMO(cor_Nmetabolism)

cortest.bartlett(cor_nodES, n = nrow(cor_nodES))
cortest.bartlett(cor_nodNE, n = nrow(cor_nodNE))
cortest.bartlett(cor_complete, n = nrow(cor_complete))
cortest.bartlett(cor_Nmetabolism, n = nrow(cor_Nmetabolism))

pca_nodES <- vegan::rda(finalscaled_nodES, scale = TRUE)
pca_nodNE <- vegan::rda(finalscaled_nodNE, scale = TRUE)
pca_complete <- vegan::rda(finalscaled_complete, scale = TRUE) 
pca_Nmetabolism <- vegan::rda(finalscaled_Nmetabolism, scale = TRUE) #PCA analysis 

biplot(pca_nodES)
biplot(pca_nodNE)
biplot(pca_complete)
biplot(pca_Nmetabolism)

head(summary(pca_nodES))
head(summary(pca_nodNE))
head(summary(pca_complete))
head(summary(pca_Nmetabolism))

sites_nodES = as.data.frame(scores(pca_nodES, display = "sites"))
sites_nodNE = as.data.frame(scores(pca_nodNE, display = "sites"))
sites_complete = as.data.frame(scores(pca_complete, display = "sites"))
sites_Nmetabolism = as.data.frame(scores(pca_Nmetabolism, display = "sites"))

#nice ggplots of the PCA analyses

#nodES

ggplot(sites_nodES,aes(x=PC1,y=PC2,color=finalmetadata$Ntreatment,shape=finalmetadata$compartment)) +
  geom_point(size=8)+
  xlab("PC 1 (24%)") +
  ylab("PC 2 (13%)") +
  labs(title = "nodES") +
  theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(size = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9)),
        axis.text.y=element_text(size=rel(0.9)))

#nodNE

ggplot(sites_nodNE,aes(x=PC1,y=PC2,color=finalmetadata$Ntreatment,shape=finalmetadata$compartment)) +
  geom_point(size=8)+
  xlab("PC 1 (25%)") +
  ylab("PC 2 (11%)") +
  labs(title = "nodNE") +
  theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(size = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9)),
        axis.text.y=element_text(size=rel(0.9)))

#complete

ggplot(sites_complete,aes(x=PC1,y=PC2,color=finalmetadata$Ntreatment,shape=finalmetadata$compartment)) +
  geom_point(size=8)+
  xlab("PC 1 (24%)") +
  ylab("PC 2 (12%)") +
  labs(title = "Whole genome") +
  theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(size = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9)),
        axis.text.y=element_text(size=rel(0.9)))

#Nmetabolism

ggplot(sites_Nmetabolism,aes(x=PC1,y=PC2,color=finalmetadata$Ntreatment,shape=finalmetadata$compartment)) +
  geom_point(size=8)+
  xlab("PC 1 (25%)") +
  ylab("PC 2 (18%)") +
  labs(title = "N metabolism") +
  theme_bw(base_size = 30) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(size = 1, colour = "black",fill=NA),
        panel.background = element_rect(fill="white"),
        axis.text.x=element_text(size=rel(0.9)),
        axis.text.y=element_text(size=rel(0.9)))

```

```{r Chunk 9: Principal coordinate analysis + plots}

#PCoA plots of each resemblance matrix


```

```{r Chunk 10: Tentative graveyard zone}

#empty as of now, since the rarefaction stuff was split off into a separate file

```

---
title: PCoA_relativeabundance_alphadiv_RAC.R
author: User
date: '2023-04-21'

---